"""Transcribe a file (PDF, image or text) to Markdown with Claude"""

import base64
import os
from pathlib import Path

import anthropic
from anthropic import Anthropic

from kwark.ai.errors import APIError
from kwark.ai.errors import KwarkAIError
from kwark.ai.errors import TruncatedResponseError
from kwark.ai.errors import UnsupportedFileTypeError
from kwark.ai.file_types import FILE_TYPES
from kwark.ai.file_types import SUPPORTED_SUFFIXES


TRANSCRIBE_PROMPT = (
    "Transcribe the contents of the file to Markdown, verbatim. If the file "
    "contains structured data such as tables, represent it as YAML code "
    "blocks within the Markdown. If there are visual elements such as "
    "diagrams, describe them precisely. If the file is mostly or entirely "
    "an image, the Markdown may consist exclusively of description.")

TRANSCRIBE_DISCLAIMER = (
    "Generated by an AI process from a binary file. Subject to errors. "
    "Tables and other structured data were converted to YAML for machine "
    "readability.")

SYSTEM_PROMPT = (
    "You convert files into Markdown documents. Respond with only the "
    "Markdown content itself: no preamble, no commentary and no code fence "
    "wrapping the whole document.")


def _file_block(path):
    """Build the content block for the file, raising UnsupportedFileTypeError
    for unsupported suffixes and KwarkAIError if the file can't be read"""
    file_type = FILE_TYPES.get(path.suffix.lower())
    if file_type is None:
        raise UnsupportedFileTypeError(
            f"Unsupported file type '{path.suffix or '(none)'}' for "
            f"{path}; supported types are {', '.join(SUPPORTED_SUFFIXES)}")
    block_type, media_type = file_type
    try:
        if media_type == 'text/plain':
            # The API's plain-text document source takes raw text, not base64
            source = {'type': 'text',
                      'data': path.read_text(encoding='utf-8')}
        else:
            source = {'type': 'base64',
                      'data': base64.standard_b64encode(
                          path.read_bytes()).decode('ascii')}
    except UnicodeDecodeError as e:
        raise KwarkAIError(f"Unable to decode {path} as UTF-8: {e}") from e
    except OSError as e:
        raise KwarkAIError(f"Unable to read {path}: {e}") from e
    return {'type': block_type,
            'source': {'media_type': media_type, **source}}


def transcribe(path, *, model='claude-opus-4-6', api_key=None,
               prompt=TRANSCRIBE_PROMPT, max_tokens=32000):
    """Transcribe a file to Markdown with Claude.

    Args:
        path: str or PathLike pointing to a .pdf, .png, .jpg, .jpeg, .gif,
            .webp, .txt, .md or .csv file
        model: Anthropic model ID
        api_key: Anthropic API key; None uses the SDK default
            (ANTHROPIC_API_KEY)
        prompt: Instructions sent alongside the file
        max_tokens: Maximum output tokens

    Returns:
        The Markdown body as a string (without TRANSCRIBE_DISCLAIMER)

    Raises:
        UnsupportedFileTypeError: the file type isn't supported
        TruncatedResponseError: the output hit max_tokens
        APIError: the Anthropic API call failed
        KwarkAIError: the file couldn't be read
    """
    path = Path(os.fspath(path))
    file_block = _file_block(path)
    messages = [{'role': 'user', 'content': [
        file_block, {'type': 'text', 'text': prompt}]}]
    try:
        client = Anthropic(api_key=api_key)
        if client.api_key is None and client.auth_token is None:
            raise APIError(
                "No Anthropic API key: pass api_key or set "
                "ANTHROPIC_API_KEY")
        with client.messages.stream(model=model, max_tokens=max_tokens,
                                    system=SYSTEM_PROMPT,
                                    messages=messages) as stream:
            message = stream.get_final_message()
    except anthropic.AnthropicError as e:
        raise APIError(
            f"Anthropic API error transcribing {path}: {e}") from e
    if message.stop_reason == 'max_tokens':
        raise TruncatedResponseError(
            f"Transcription of {path} was truncated at max_tokens="
            f"{max_tokens}; increase max_tokens or split the file")
    return ''.join(b.text for b in message.content if b.type == 'text')
